[env]
HK_MISE = 1

[tools]
harper-cli = "latest"
hk = "latest"
pkl = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
vale = "latest"
"aqua:betterleaks/betterleaks" = "latest"

[hooks]
enter = "hk install --mise"
postinstall = "hk install --mise"

[tasks."check"]
description = "Run static analysis for changed files."
run = "hk run check"

[tasks."check:all"]
description = "Run static analysis for all files."
run = "hk run check --all"
