[tools]
cilium-cli = "latest"
cilium-hubble = "latest"
cmctl = "latest"
helm = "latest"
helm-ls = "latest"
k9s = "latest"
kind = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubelogin = "latest"
velero = "latest"
"go:github.com/erikkinding/sk" = "0.3.9"
