[tools]
cilium-cli = "latest"
cilium-hubble = "latest"
cmctl = "latest"
helm = "latest"
k9s = "latest"
kind = "latest"
kubebuilder = "latest"
kubectl = "latest"
kubelogin = "latest"
velero = "latest"
"github:erikkinding/sk" = "latest"
"github:nklmilojevic/sofka" = "latest"
